### PR TITLE
add support for rspec-puppet and beaker automated testing

### PR DESCRIPTION
**Pull request by lmayorga1980**

### CODE REVIEW

**Comment by lmayorga1980** [comment]
@abuxton something tells me that the CI configuration is wrong because I just change a space inside the `params.pp` string.

**Comment by abuxton** [comment]
@lmayorga1980  Can you not change the Notify resources to notice functions, they are declared as notify so that when run in --noop mode the whole module reports in the console and changes are shown for those classes it is a desired feature of how i orchestrated the module.

**Comment by lmayorga1980** [comment]
@abuxton, I missed that and planning to rollback the `notice` to `notify`. :+1:

**Comment by lmayorga1980** [comment]
@abuxton I fixed the `notify` overwrites and also added some extra features for testing.

**Pull request closed without merging**
